# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format: json                            # All responses should be JSON formated
    include_format: false                           # We do not include format in request, so that all responses
    # will eventually be JSON formated
  body_converter:
    enabled: true
